const resume = {
  personalInfo: {
    name: "Utkarsh Upadhyay",
    title: "B.Tech Computer Science undergraduate",
    location: "Lucknow, India",
    phone: "+91 8303769534",
    email: "uutkarsh952@gmail.com",
    website: "",
    linkedin: "linkedin.com/in/utkarsh2005",
    github: "github.com/upadhyayutkarsh2005",
  },
  summary:
    "B.Tech Computer Science undergraduate with strong expertise in Machine Learning and Generative AI, including LLMs, RAG pipelines, agentic workflows, and model fine-tuning. Experienced in designing and deploying end-to-end AI systems using FastAPI backends, scalable APIs, and production-oriented ML pipelines. Passionate about building intelligent, real-world AI applications.",
  skills: {
    languages: ["Python", "Java", "C"],
    frameworksAndTools: [
      "PyTorch",
      "scikit-learn",
      "Hugging Face",
      "OpenCV",
      "FastAPI",
      "Flask",
      "REST APIs",
      "Streamlit",
      "MongoDB",
      "SQL",
      "Git",
      "Docker",
      "Postman",
      "AWS",
      "GCP",
      "VS Code",
      "n8n",
    ],
    softSkills: [],
  },
  experience: [
    {
      company: "Kreativetimebox",
      position: "Python & ML Intern",
      location: "Hyderabad, India",
      startDate: "May 2025",
      endDate: "Sept 2025",
      isCurrentRole: false,
      description: [
        "Built and deployed production ML pipelines for structured data extraction and processing.",
        "Exposed fraud detection, classification, and anomaly detection models via FastAPI and REST APIs.",
        "Optimized model inference and deployments using Agile and Git-based workflows.",
      ],
      technologies: ["Python", "ML", "FastAPI", "REST APIs", "Agile", "Git"],
    },
    {
      company: "FalkomeAI",
      position: "Generative AI Intern",
      location: "Maharashtra, India",
      startDate: "Nov 2025",
      endDate: "Present",
      isCurrentRole: true,
      description: [
        "Built an LLM-powered AI agent for ISP customer support and technical troubleshooting.",
        "Fine-tuned Mistral LLM for domain-specific intent classification and query resolution.",
        "Implemented a RAG pipeline using embeddings and vector databases for context-aware responses.",
      ],
      technologies: ["LLM", "Mistral", "RAG", "embeddings", "vector databases"],
    },
  ],
  projects: [
    {
      name: "DigiSanjeevani",
      role: "",
      startDate: "",
      endDate: "",
      description: [
        "Developed a full-stack AI-powered healthcare platform featuring symptom analysis, medical report parsing, doctor booking, chatbot, and hospital locator.",
        "Integrated LLM-based medical insights using Gemini API with FastAPI backend and MongoDB for structured health data storage.",
      ],
      technologies: ["AI", "healthcare", "Gemini API", "FastAPI", "MongoDB"],
      link: "GitHub",
    },
    {
      name: "SmartDoc Parser – Invoice & Bank Statement Extraction",
      role: "",
      startDate: "",
      endDate: "",
      description: [
        "Developed a scalable document intelligence pipeline for extracting structured data from financial documents.",
        "Integrated OCR (DocTr, PaddleOCR) with LLM-driven JSON extraction for layout-agnostic parsing.",
        "Reduced third-party API dependency through custom model fine-tuning.",
      ],
      technologies: ["OCR", "DocTr", "PaddleOCR", "LLM", "JSON extraction"],
      link: "GitHub",
    },
  ],
  education: [
    {
      university: "A.P.J Abdul Kalam Technical University",
      degree: "B.Tech",
      branch: "Computer Science and Engineering",
      location: "Lucknow, UP",
      sgpa: "",
      startDate: "2022",
      endDate: "2026",
    },
    {
      university: "S.R Global School",
      degree: "",
      branch: "",
      location: "",
      sgpa: "",
      startDate: "2018",
      endDate: "2022",
    },
  ],
  extracurricular: [
    "GDG On Campus Oct 2023 – July 2025",
    "Event Management Co-lead BIET Lucknow — Led and organized technical events with cross-department participation",
  ],
  customSections: [
    {
      title: "Certifications",
      items: [
        "AWS Cloud Practitioner Essentials",
        "Google Cloud Study Jams (GDG)",
        "Java Web Development Program with AI (HCLTech)",
      ],
    },
  ],
};
