import { Resume } from "./lib/types";

export const resume_x: Resume = {
  skills: {
    languages: ["Java", "HTML", "CSS", "TypeScript", "JavaScript"],
    softSkills: ["Communication", "Problem Solver"],
    frameworksAndTools: [
      "React",
      "Firebase",
      "Tailwind CSS",
      "Supabase",
      "Flutter",
      "Vite",
      "Git",
      "GitHub",
      "Next.js",
    ],
  },
  summary:
    "Aspiring software developer with 4+ years of experience in app and web development, building full-stack projects with React, Firebase, and Flutter. Passionate about solving real-world problems and seeking impactful roles in globally recognized tech companies.",
  projects: [
    {
      link: "https://minomap.vercel.app",
      name: "MinoMap AI",
      role: "Mind Mapping Tool - Organize Ideas Smarter",
      endDate: "Present",
      startDate: "Sep 2025",
      description: [
        "Implemented AI-driven mapping that helps users visualize and organize information effortlessly",
        "A tool that converts unstructured ideas into clear, connected knowledge maps.",
      ],
      technologies: ["Next.js", "Supabase"],
    },
    {
      link: "https://alphaomega.pages.dev",
      name: "Alpha Omega",
      role: "Social Media App",
      endDate: "July 2025",
      startDate: "July 2024",
      description: [
        "Built a minimalistic, scalable social media app.",
        "Features include image and text posting, user authentication, blocking, and real-time chat.",
      ],
      technologies: ["React", "Firebase", "Vite"],
    },
    {
      link: "",
      name: "Wassup - A messaging app",
      role: "Messaging application with socket.io",
      endDate: "Oct 2024",
      startDate: "Aug 2024",
      description: [
        "Designed a clean, mobile-friendly user interface for a real-time messaging application similar to WhatsApp.",
        "Implemented core chat features, including real-time one-to-one messaging, user search, and seamless screen transitions.",
        "Built secure and scalable real-time communication using Socket.IO",
      ],
      technologies: [
        "React",
        "React Native",
        "Socket.io",
        "Sentry",
        "Express",
        "Node.js",
        "Clerk",
        "Mongodb",
      ],
    },
    {
      link: "https://project-51.pages.dev",
      name: "OneBox",
      role: "Productivity Manager (previously known as Project - 51)",
      endDate: "May 2024",
      startDate: "Sep 2023",
      description: [
        "A super app for tasks, to-dos, reminders, and expense tracking.",
        "Created an intuitive interface for daily reviews and weekly insights.",
      ],
      technologies: ["Flutter", "Dart"],
    },
    {
      link: "https://wrkks.site",
      name: "Wrkks",
      role: "Resume to website",
      endDate: "Feb 2025",
      startDate: "Feb 2025",
      description: [
        "Stop wrestling with website builders. Drop your LinkedIn PDF or upload a resume PDF, and we'll instantly generate a professional, high-converting personal site that gets you hired.",
      ],
      technologies: [],
    },
  ],
  education: [
    {
      sgpa: "8.72",
      branch: "Computer Science & Engineering",
      degree: "B.Tech",
      endDate: "2027",
      location: "Lucknow",
      startDate: "2023",
      university: "Dr. A. P. J. Abdul Kalam Technical University, Lucknow",
    },
  ],
  experience: [],
  personalInfo: {
    name: "Kumar Utkarsh",
    email: "utkarshh2705@gmail.com",
    phone: "+919027351416",
    title: "Full Stack Web Developer",
    github: "",
    twitter: "",
    website: "https://utkarshh.pages.dev",
    imageUrl: "",
    linkedin: "",
    location: "Lucknow, UP",
  },
  customSections: [],
  extracurricular: [
    "Google Developer Groups (GDG)",
    "Contribute to the GDG Web team through tech discussions, event support, and resource management.",
  ],
};
