import NavBar from "@/components/nav-bar";
import { AnchoredToastProvider, ToastProvider } from "@/components/ui/toast";
import { TanStackQueryProvider } from "@/providers/tanstack-provider";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Bricolage_Grotesque, Geist_Mono } from "next/font/google";
import "./globals.css";

const bricolage = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Wrkks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${bricolage.className} ${geistMono.variable} antialiased`}
        >
          <TanStackQueryProvider>
            <ToastProvider>
              <AnchoredToastProvider>
                <ThemeProvider
                  attribute="class"
                  defaultTheme="system"
                  enableSystem
                  disableTransitionOnChange
                >
                  <NavBar />
                  {children}
                </ThemeProvider>
              </AnchoredToastProvider>
            </ToastProvider>
          </TanStackQueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
